### ISSUE TITLE
findManyByIds is broken in last version

### ISSUE THREAD

**Issue by vasily-polonsky** [GraphQLGuide/apollo-datasource-mongodb#60]
Updated from 0.2.8 to 0.4.0 (also to 0.3.2) and mentioned that method findManyByIds is broken in new versions.
it returns different values compared to the native request

![Screenshot 2021-05-26 at 17 22 33](https://user-images.githubusercontent.com/6172199/119686775-f6a61600-be46-11eb-9f5a-bd34b53b0aaa.png)

![Screenshot 2021-05-26 at 17 27 12](https://user-images.githubusercontent.com/6172199/119687583-9e234880-be47-11eb-8ff0-c05f9f8ab581.png)

![Screenshot 2021-05-26 at 17 27 27](https://user-images.githubusercontent.com/6172199/119687621-a5e2ed00-be47-11eb-9b57-5a58e99bc137.png)

**Comment by lorensr** [comment]
Oh no, thanks for reporting! I'm not sure where exactly the bug is. There's nothing in the [changelog](https://github.com/GraphQLGuide/apollo-datasource-mongodb/releases) between `0.2.8` and `0.3.2` that stands out as a culprit. 

Is there a pattern to the different results? In your screenshots, it looks like the results might be the same except for the third result being `undefined`? Is there anything peculiar about that doc?

I'd like to update this test case to cover the bug:

https://github.com/GraphQLGuide/apollo-datasource-mongodb/blob/master/src/__tests__/cache.test.js#L126

And then fix it and publish a `0.4.1`.

**Comment by jonasmeier1212** [comment]
I have found the reason for this error:
In https://github.com/GraphQLGuide/apollo-datasource-mongodb/blob/master/src/cache.js#L8 the following check is used:
```typescript
if (ObjectId.isValid(str)) {
    return new ObjectId(str)
}
```

But the problem is, that `isValid` returns `true` for all strings of length=12.
https://www.geeksforgeeks.org/how-to-check-if-a-string-is-valid-mongodb-objectid-in-nodejs/
 
In Vasilys case the Ids are strings, but sometimes are converted to ObjectIDs and therefore can not be found, although they exist.

I will open a PR for fixing this issue later.

**Comment by lorensr** [comment]
Great, thanks!
