### ISSUE TITLE
this.findManyByIds/this.findByFields is not a function

### ISSUE THREAD

**Issue by flyboarder** [GraphQLGuide/apollo-datasource-mongodb#86]
When attempting to run with ts-jest, we get the following error:

```
TypeError: this.findManyByIds is not a function
```

```
export class UsersDataSource extends MongoDataSource<UserDocument, Context> {
  constructor () {
    super(User) // pass User model to MongoDataSource
  }
  
  async fetchUsers (ids: (ObjectId | string)[]) {
    // return this.model.find({ _id: { '$in': ids }});
    return this.findManyByIds(ids); // TODO: fix findByFields/findManyByIds is not a function?
  }
```

This happens for all the internal caching functions.

**Comment by namirsab** [comment]
hey @flyboarder 
I had the same issue. The problem is that this data sources are meant to be used within apollo server. Apollo calls the `initialize` method, and these methods are added there.

https://github.com/GraphQLGuide/apollo-datasource-mongodb/blob/master/src/datasource.js#L30

You can fake this by calling it in your tests. Hope that helps!

**Comment by lorensr** [comment]
That's correct, thanks @namirsab !
